# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-08-17 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('cre_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modi_date', models.DateTimeField(auto_now=True, verbose_name='date modified')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='likes')),
                ('topped', models.BooleanField(default=False, verbose_name='Top')),
            ],
        ),
    ]
