# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-09-30 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterlist',
            name='dirpath',
        ),
    ]
