# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-09-27 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20170826_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='twitteraccount')),
                ('user', models.CharField(max_length=20, verbose_name='twitteruser')),
                ('img', models.ImageField(upload_to='img')),
                ('dirpath', models.CharField(max_length=30, verbose_name='dirpath')),
            ],
        ),
    ]
