# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-09-27 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_twitter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Twitter',
            new_name='Twitterlist',
        ),
    ]
