# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2017-09-29 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20170927_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterlist',
            name='img',
            field=models.ImageField(upload_to='apps/static/apps/img'),
        ),
    ]
